name = "IJuliaUpdater"
uuid = "a6800a9c-a421-4a0a-89d6-efa8c4398112"
authors = ["Bruno Amorim <amorim.bac@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
