name = "IJuliaUpdater"
uuid = "a6800a9c-a421-4a0a-89d6-efa8c4398112"
authors = ["Bruno Amorim <amorim.bac@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
